const db = require('../essentials/dbUtils');
const logger = require('../essentials/logger');

/**
 * 🎯 **Fetches Rank Emojis from the Database**
 *
 * Queries the `guild_emojis` table to retrieve stored emoji formats based on predefined rank keys.
 * Replaces hardcoded emoji strings with dynamically loaded ones.
 *
 * @async
 * @function fetchRankEmojis
 * @returns {Promise<Object>} - A dictionary mapping rank names to their emoji formats.
 *
 * @example
 * const rankEmojis = await fetchRankEmojis();
 * console.log(rankEmojis.owner); // <:Clan_icon__Owner:1223270860152901816>
 */
async function fetchRankEmojis() {
    try {
        const emojiRows = await db.guild.getAll('SELECT emoji_key, emoji_format FROM guild_emojis');
        const emojiMap = emojiRows.reduce((acc, { emoji_key, emoji_format }) => {
            acc[emoji_key.replace('emoji_', '')] = emoji_format;
            return acc;
        }, {});

        logger.info('✅ Rank emojis loaded successfully from the database.');
        return emojiMap;
    } catch (error) {
        logger.error(`❌ Error fetching rank emojis: ${error.message}`);
        return {};
    }
}

/**
 * 🎭 **Defines Rank Metadata**
 *
 * Each rank contains:
 * - **emoji**: Loaded dynamically from the database, with a fallback `❌` emoji.
 * - **role**: The Discord role name for the rank.
 * - **color**: The hex color associated with the role.
 * @returns
 */
async function getRanks() {
    const rankEmojis = await fetchRankEmojis();

    return {
        owner: { emoji: rankEmojis.owner || '❌', role: 'Owner', color: 0xffff00 },
        'deputy owner': { emoji: rankEmojis.deputy_owner || '❌', role: 'Deputy owner', color: 0xdfefd6 },
        administrator: { emoji: rankEmojis.administrator || '❌', role: 'Administrator', color: 0xeea143 },
        moderator: { emoji: rankEmojis.moderator || '❌', role: 'Moderator', color: 0xfffbc3 },
        private: { emoji: rankEmojis.private || '❌', role: 'Private', color: 0x3f3f3f },
        healer: { emoji: rankEmojis.healer || '❌', role: 'Nurse', color: 0x178c51 },
        coordinator: { emoji: rankEmojis.coordinator || '❌', role: 'Bingo Jury', color: 0x443310 },
        specialist: { emoji: rankEmojis.specialist || '❌', role: 'Special', color: 0xe42801 },
        bronze: { emoji: rankEmojis.bronze || '❌', role: 'Bronze', color: 0x9c643a },
        iron: { emoji: rankEmojis.iron || '❌', role: 'Iron', color: 0x565958 },
        steel: { emoji: rankEmojis.steel || '❌', role: 'Steel', color: 0x9c9c9c },
        mithril: { emoji: rankEmojis.mithril || '❌', role: 'Mithril', color: 0x4441bf },
        adamant: { emoji: rankEmojis.adamant || '❌', role: 'Adamant', color: 0x258f4a },
        rune: { emoji: rankEmojis.rune || '❌', role: 'Rune', color: 0x368eb4 },
        dragon: { emoji: rankEmojis.dragon || '❌', role: 'Dragon', color: 0xbe2532 },
        onyx: { emoji: rankEmojis.onyx || '❌', role: 'Onyx', color: 0x151515 },
        zenyte: { emoji: rankEmojis.zenyte || '❌', role: 'Zenyte', color: 0xe47a1a },
        legend: { emoji: rankEmojis.legend || '❌', role: 'Legend', color: 0xd7debd },
        myth: { emoji: rankEmojis.myth || '❌', role: 'Myth', color: 0x2884c2 },
        tztok: { emoji: rankEmojis.tztok || '❌', role: 'TzTok', color: 0xfec102 },
        tzkal: { emoji: rankEmojis.tzkal || '❌', role: 'TzKal', color: 0xc4550b },
        soul: { emoji: rankEmojis.soul || '❌', role: 'Soul', color: 0xa8aef1 },
        competitor: { emoji: rankEmojis.competitor || '❌', role: 'Competitor', color: 0x48de6f },
        helper: { emoji: rankEmojis.helper || '❌', role: 'Helper', color: 0xf0e23a },
        looter: { emoji: rankEmojis.looter || '❌', role: 'Looter', color: 0xa40cc5 },
        quester: { emoji: rankEmojis.quester || '❌', role: 'Quester', color: 0x3a7fdc },
        wild: { emoji: rankEmojis.wild || '❌', role: 'Wild', color: 0x434343 },
        // PLACEHOLDERS: Colors not on point, Generic Role Names
        achiever: { emoji: rankEmojis.achiever || '❌', role: 'Achiever', color: 0xffd700 },
        adept: { emoji: rankEmojis.adept || '❌', role: 'Adept', color: 0xc0c0c0 },
        admiral: { emoji: rankEmojis.admiral || '❌', role: 'Admiral', color: 0x000080 },
        adventurer: { emoji: rankEmojis.adventurer || '❌', role: 'Adventurer', color: 0x008000 },
        air: { emoji: rankEmojis.air || '❌', role: 'Air', color: 0x87ceeb },
        anchor: { emoji: rankEmojis.anchor || '❌', role: 'Anchor', color: 0x708090 },
        apothecary: { emoji: rankEmojis.apothecary || '❌', role: 'Apothecary', color: 0x8a2be2 },
        archer: { emoji: rankEmojis.archer || '❌', role: 'Archer', color: 0x32cd32 },
        armadylean: { emoji: rankEmojis.armadylean || '❌', role: 'Armadylean', color: 0x556b2f },
        artillery: { emoji: rankEmojis.artillery || '❌', role: 'Artillery', color: 0xa52a2a },
        artisan: { emoji: rankEmojis.artisan || '❌', role: 'Artisan', color: 0xd2b48c },
        asgarnian: { emoji: rankEmojis.asgarnian || '❌', role: 'Asgarnian', color: 0xdeb887 },
        assassin: { emoji: rankEmojis.assassin || '❌', role: 'Assassin', color: 0x000000 },
        assistant: { emoji: rankEmojis.assistant || '❌', role: 'Assistant', color: 0x808080 },
        astral: { emoji: rankEmojis.astral || '❌', role: 'Astral', color: 0x4b0082 },
        athlete: { emoji: rankEmojis.athlete || '❌', role: 'Athlete', color: 0xff4500 },
        attacker: { emoji: rankEmojis.attacker || '❌', role: 'Attacker', color: 0xdc143c },
        bandit: { emoji: rankEmojis.bandit || '❌', role: 'Bandit', color: 0x8b0000 },
        bandosian: { emoji: rankEmojis.bandosian || '❌', role: 'Bandosian', color: 0xb22222 },
        barbarian: { emoji: rankEmojis.barbarian || '❌', role: 'Barbarian', color: 0x800000 },
        battlemage: { emoji: rankEmojis.battlemage || '❌', role: 'Battlemage', color: 0x483d8b },
        beast: { emoji: rankEmojis.beast || '❌', role: 'Beast', color: 0x8b4513 },
        berserker: { emoji: rankEmojis.berserker || '❌', role: 'Berserker', color: 0xff0000 },
        blisterwood: { emoji: rankEmojis.blisterwood || '❌', role: 'Blisterwood', color: 0xcd5c5c },
        blood: { emoji: rankEmojis.blood || '❌', role: 'Blood', color: 0x660000 },
        blue: { emoji: rankEmojis.blue || '❌', role: 'Blue', color: 0x0000ff },
        bob: { emoji: rankEmojis.bob || '❌', role: 'Bob', color: 0xff8c00 },
        body: { emoji: rankEmojis.body || '❌', role: 'Body', color: 0xd3d3d3 },
        brassican: { emoji: rankEmojis.brassican || '❌', role: 'Brassican', color: 0xcd853f },
        brawler: { emoji: rankEmojis.brawler || '❌', role: 'Brawler', color: 0xa0522d },
        brigadier: { emoji: rankEmojis.brigadier || '❌', role: 'Brigadier', color: 0x2e8b57 },
        brigand: { emoji: rankEmojis.brigand || '❌', role: 'Brigand', color: 0x6b8e23 },
        bruiser: { emoji: rankEmojis.bruiser || '❌', role: 'Bruiser', color: 0x778899 },
        bulwark: { emoji: rankEmojis.bulwark || '❌', role: 'Bulwark', color: 0x2f4f4f },
        burglar: { emoji: rankEmojis.burglar || '❌', role: 'Burglar', color: 0x808000 },
        burnt: { emoji: rankEmojis.burnt || '❌', role: 'Burnt', color: 0xb8860b },
        cadet: { emoji: rankEmojis.cadet || '❌', role: 'Cadet', color: 0x5f9ea0 },
        captain: { emoji: rankEmojis.captain || '❌', role: 'Captain', color: 0x191970 },
        carry: { emoji: rankEmojis.carry || '❌', role: 'Carry', color: 0xd2691e },
        champion: { emoji: rankEmojis.champion || '❌', role: 'Champion', color: 0xffdf00 },
        chaos: { emoji: rankEmojis.chaos || '❌', role: 'Chaos', color: 0x9400d3 },
        cleric: { emoji: rankEmojis.cleric || '❌', role: 'Cleric', color: 0xf5deb3 },
        collector: { emoji: rankEmojis.collector || '❌', role: 'Collector', color: 0xdaa520 },
        colonel: { emoji: rankEmojis.colonel || '❌', role: 'Colonel', color: 0x9932cc },
        commander: { emoji: rankEmojis.commander || '❌', role: 'Commander', color: 0x00008b },
        completionist: { emoji: rankEmojis.completionist || '❌', role: 'Completionist', color: 0x008b8b },
        constructor: { emoji: rankEmojis.constructor || '❌', role: 'Constructor', color: 0xb0c4de },
        cook: { emoji: rankEmojis.cook || '❌', role: 'Cook', color: 0xff6347 },
        corporal: { emoji: rankEmojis.corporal || '❌', role: 'Corporal', color: 0x8fbc8f },
        cosmic: { emoji: rankEmojis.cosmic || '❌', role: 'Cosmic', color: 0x6a5acd },
        councillor: { emoji: rankEmojis.councillor || '❌', role: 'Councillor', color: 0x3cb371 },
        crafter: { emoji: rankEmojis.crafter || '❌', role: 'Crafter', color: 0xf4a460 },
        crew: { emoji: rankEmojis.crew || '❌', role: 'Crew', color: 0x808080 },
        crusader: { emoji: rankEmojis.crusader || '❌', role: 'Crusader', color: 0x8b0000 },
        cutpurse: { emoji: rankEmojis.cutpurse || '❌', role: 'Cutpurse', color: 0xffe4b5 },
        death: { emoji: rankEmojis.death || '❌', role: 'Death', color: 0x000000 },
        defender: { emoji: rankEmojis.defender || '❌', role: 'Defender', color: 0x006400 },
        defiler: { emoji: rankEmojis.defiler || '❌', role: 'Defiler', color: 0x800080 },
        destroyer: { emoji: rankEmojis.destroyer || '❌', role: 'Destroyer', color: 0xdc143c },
        diamond: { emoji: rankEmojis.diamond || '❌', role: 'Diamond', color: 0xb9f2ff },
        diseased: { emoji: rankEmojis.diseased || '❌', role: 'Diseased', color: 0x808000 },
        doctor: { emoji: rankEmojis.doctor || '❌', role: 'Doctor', color: 0xff1493 },
        dogsbody: { emoji: rankEmojis.dogsbody || '❌', role: 'Dogsbody', color: 0x708090 },
        dragonstone: { emoji: rankEmojis.dragonstone || '❌', role: 'Dragonstone', color: 0x2e2e2e },
        druid: { emoji: rankEmojis.druid || '❌', role: 'Druid', color: 0x228b22 },
        duellist: { emoji: rankEmojis.duellist || '❌', role: 'Duellist', color: 0xdc143c },
        earth: { emoji: rankEmojis.earth || '❌', role: 'Earth', color: 0x8b4513 },
        elite: { emoji: rankEmojis.elite || '❌', role: 'Elite', color: 0xdaa520 },
        emerald: { emoji: rankEmojis.emerald || '❌', role: 'Emerald', color: 0x50c878 },
        enforcer: { emoji: rankEmojis.enforcer || '❌', role: 'Enforcer', color: 0xff0000 },
        epic: { emoji: rankEmojis.epic || '❌', role: 'Epic', color: 0x9400d3 },
        executive: { emoji: rankEmojis.executive || '❌', role: 'Executive', color: 0x191970 },
        expert: { emoji: rankEmojis.expert || '❌', role: 'Expert', color: 0x008b8b },
        explorer: { emoji: rankEmojis.explorer || '❌', role: 'Explorer', color: 0x00ced1 },
        farmer: { emoji: rankEmojis.farmer || '❌', role: 'Farmer', color: 0x6b8e23 },
        feeder: { emoji: rankEmojis.feeder || '❌', role: 'Feeder', color: 0xff8c00 },
        fighter: { emoji: rankEmojis.fighter || '❌', role: 'Fighter', color: 0xb22222 },
        fire: { emoji: rankEmojis.fire || '❌', role: 'Fire', color: 0xff6347 },
        firemaker: { emoji: rankEmojis.firemaker || '❌', role: 'Firemaker', color: 0xff7f50 },
        firestarter: { emoji: rankEmojis.firestarter || '❌', role: 'Firestarter', color: 0xff7f50 },
        fisher: { emoji: rankEmojis.fisher || '❌', role: 'Fisher', color: 0x1e90ff },
        fletcher: { emoji: rankEmojis.fletcher || '❌', role: 'Fletcher', color: 0xda70d6 },
        forager: { emoji: rankEmojis.forager || '❌', role: 'Forager', color: 0x8fbc8f },
        fremennik: { emoji: rankEmojis.fremennik || '❌', role: 'Fremennik', color: 0x8b4513 },
        gamer: { emoji: rankEmojis.gamer || '❌', role: 'Gamer', color: 0x00ff00 },
        gatherer: { emoji: rankEmojis.gatherer || '❌', role: 'Gatherer', color: 0x3cb371 },
        general: { emoji: rankEmojis.general || '❌', role: 'General', color: 0x696969 },
        'gnome child': { emoji: rankEmojis.gnome_child || '❌', role: 'Gnome Child', color: 0xff69b4 },
        'gnome elder': { emoji: rankEmojis.gnome_elder || '❌', role: 'Gnome Elder', color: 0xc71585 },
        goblin: { emoji: rankEmojis.goblin || '❌', role: 'Goblin', color: 0x9acd32 },
        gold: { emoji: rankEmojis.gold || '❌', role: 'Gold', color: 0xffd700 },
        goon: { emoji: rankEmojis.goon || '❌', role: 'Goon', color: 0x708090 },
        green: { emoji: rankEmojis.green || '❌', role: 'Green', color: 0x008000 },
        grey: { emoji: rankEmojis.grey || '❌', role: 'Grey', color: 0x808080 },
        guardian: { emoji: rankEmojis.guardian || '❌', role: 'Guardian', color: 0x2f4f4f },
        guest: { emoji: rankEmojis.guest || '❌', role: 'Guest', color: 0xd3d3d3 },
        guthixian: { emoji: rankEmojis.guthixian || '❌', role: 'Guthixian', color: 0x7cfc00 },
        harpoon: { emoji: rankEmojis.harpoon || '❌', role: 'Harpoon', color: 0x4682b4 },
        hellcat: { emoji: rankEmojis.hellcat || '❌', role: 'Hellcat', color: 0x8b0000 },
        herbologist: { emoji: rankEmojis.herbologist || '❌', role: 'Herbologist', color: 0x6b8e23 },
        hero: { emoji: rankEmojis.hero || '❌', role: 'Hero', color: 0xffdf00 },
        hoarder: { emoji: rankEmojis.hoarder || '❌', role: 'Hoarder', color: 0x8b4513 },
        holy: { emoji: rankEmojis.holy || '❌', role: 'Holy', color: 0xffffff },
        hunter: { emoji: rankEmojis.hunter || '❌', role: 'Hunter', color: 0x006400 },
        ignitor: { emoji: rankEmojis.ignitor || '❌', role: 'Ignitor', color: 0xff7f50 },
        illusionist: { emoji: rankEmojis.illusionist || '❌', role: 'Illusionist', color: 0x9932cc },
        imp: { emoji: rankEmojis.imp || '❌', role: 'Imp', color: 0xff00ff },
        infantry: { emoji: rankEmojis.infantry || '❌', role: 'Infantry', color: 0x708090 },
        inquisitor: { emoji: rankEmojis.inquisitor || '❌', role: 'Inquisitor', color: 0xb22222 },
        jade: { emoji: rankEmojis.jade || '❌', role: 'Jade', color: 0x00a86b },
        'jagex moderator': { emoji: rankEmojis.jagex_moderator || '❌', role: 'Jagex Moderator', color: 0xff69b4 },
        justiciar: { emoji: rankEmojis.justiciar || '❌', role: 'Justiciar', color: 0x800000 },
        kandarin: { emoji: rankEmojis.kandarin || '❌', role: 'Kandarin', color: 0x5f9ea0 },
        karamjan: { emoji: rankEmojis.karamjan || '❌', role: 'Karamjan', color: 0xcd853f },
        kharidian: { emoji: rankEmojis.kharidian || '❌', role: 'Kharidian', color: 0x556b2f },
        kitten: { emoji: rankEmojis.kitten || '❌', role: 'Kitten', color: 0xffc0cb },
        knight: { emoji: rankEmojis.knight || '❌', role: 'Knight', color: 0x000080 },
        labourer: { emoji: rankEmojis.labourer || '❌', role: 'Labourer', color: 0xa9a9a9 },
        law: { emoji: rankEmojis.law || '❌', role: 'Law', color: 0x0000cd },
        leader: { emoji: rankEmojis.leader || '❌', role: 'Leader', color: 0xffd700 },
        learner: { emoji: rankEmojis.learner || '❌', role: 'Learner', color: 0xadd8e6 },
        legacy: { emoji: rankEmojis.legacy || '❌', role: 'Legacy', color: 0x808080 },
        legionnaire: { emoji: rankEmojis.legionnaire || '❌', role: 'Legionnaire', color: 0x8b4513 },
        lieutenant: { emoji: rankEmojis.lieutenant || '❌', role: 'Lieutenant', color: 0x00008b },
        lumberjack: { emoji: rankEmojis.lumberjack || '❌', role: 'Lumberjack', color: 0x8b4513 },
        magic: { emoji: rankEmojis.magic || '❌', role: 'Magic', color: 0x9400d3 },
        magician: { emoji: rankEmojis.magician || '❌', role: 'Magician', color: 0x9932cc },
        major: { emoji: rankEmojis.major || '❌', role: 'Major', color: 0x8b0000 },
        maple: { emoji: rankEmojis.maple || '❌', role: 'Maple', color: 0xd2691e },
        marshal: { emoji: rankEmojis.marshal || '❌', role: 'Marshal', color: 0x000080 },
        master: { emoji: rankEmojis.master || '❌', role: 'Master', color: 0xffd700 },
        maxed: { emoji: rankEmojis.maxed || '❌', role: 'Maxed', color: 0xc0c0c0 },
        mediator: { emoji: rankEmojis.mediator || '❌', role: 'Mediator', color: 0xffb6c1 },
        medic: { emoji: rankEmojis.medic || '❌', role: 'Medic', color: 0xff69b4 },
        mentor: { emoji: rankEmojis.mentor || '❌', role: 'Mentor', color: 0x008080 },
        merchant: { emoji: rankEmojis.merchant || '❌', role: 'Merchant', color: 0xdaa520 },
        mind: { emoji: rankEmojis.mind || '❌', role: 'Mind', color: 0x7fff00 },
        miner: { emoji: rankEmojis.miner || '❌', role: 'Miner', color: 0xcd853f },
        minion: { emoji: rankEmojis.minion || '❌', role: 'Minion', color: 0x8b4513 },
        misthalinian: { emoji: rankEmojis.misthalinian || '❌', role: 'Misthalinian', color: 0x808080 },
        monarch: { emoji: rankEmojis.monarch || '❌', role: 'Monarch', color: 0xda70d6 },
        morytanian: { emoji: rankEmojis.morytanian || '❌', role: 'Morytanian', color: 0x4b0082 },
        mystic: { emoji: rankEmojis.mystic || '❌', role: 'Mystic', color: 0x8a2be2 },
        natural: { emoji: rankEmojis.natural || '❌', role: 'Natural', color: 0x228b22 },
        nature: { emoji: rankEmojis.nature || '❌', role: 'Nature', color: 0x32cd32 },
        necromancer: { emoji: rankEmojis.necromancer || '❌', role: 'Necromancer', color: 0x4b0082 },
        ninja: { emoji: rankEmojis.ninja || '❌', role: 'Ninja', color: 0x000000 },
        noble: { emoji: rankEmojis.noble || '❌', role: 'Noble', color: 0xdaa520 },
        novice: { emoji: rankEmojis.novice || '❌', role: 'Novice', color: 0xd3d3d3 },
        nurse: { emoji: rankEmojis.nurse || '❌', role: 'Nurse', color: 0xffb6c1 },
        oak: { emoji: rankEmojis.oak || '❌', role: 'Oak', color: 0x8b4513 },
        officer: { emoji: rankEmojis.officer || '❌', role: 'Officer', color: 0x00008b },
        opal: { emoji: rankEmojis.opal || '❌', role: 'Opal', color: 0xe0ffff },
        oracle: { emoji: rankEmojis.oracle || '❌', role: 'Oracle', color: 0xffa500 },
        orange: { emoji: rankEmojis.orange || '❌', role: 'Orange', color: 0xffa500 },
        page: { emoji: rankEmojis.page || '❌', role: 'Page', color: 0xf0e68c },
        paladin: { emoji: rankEmojis.paladin || '❌', role: 'Paladin', color: 0x4169e1 },
        pawn: { emoji: rankEmojis.pawn || '❌', role: 'Pawn', color: 0xa9a9a9 },
        pilgrim: { emoji: rankEmojis.pilgrim || '❌', role: 'Pilgrim', color: 0x8b4513 },
        pine: { emoji: rankEmojis.pine || '❌', role: 'Pine', color: 0x228b22 },
        pink: { emoji: rankEmojis.pink || '❌', role: 'Pink', color: 0xffc0cb },
        prefect: { emoji: rankEmojis.prefect || '❌', role: 'Prefect', color: 0xda70d6 },
        priest: { emoji: rankEmojis.priest || '❌', role: 'Priest', color: 0xf5f5dc },
        prodigy: { emoji: rankEmojis.prodigy || '❌', role: 'Prodigy', color: 0xff4500 },
        proselyte: { emoji: rankEmojis.proselyte || '❌', role: 'Proselyte', color: 0x9370db },
        prospector: { emoji: rankEmojis.prospector || '❌', role: 'Prospector', color: 0xcd853f },
        protector: { emoji: rankEmojis.protector || '❌', role: 'Protector', color: 0x2e8b57 },
        pure: { emoji: rankEmojis.pure || '❌', role: 'Pure', color: 0xffffff },
        purple: { emoji: rankEmojis.purple || '❌', role: 'Purple', color: 0x800080 },
        pyromancer: { emoji: rankEmojis.pyromancer || '❌', role: 'Pyromancer', color: 0xff6347 },
        racer: { emoji: rankEmojis.racer || '❌', role: 'Racer', color: 0x1e90ff },
        raider: { emoji: rankEmojis.raider || '❌', role: 'Raider', color: 0x8b0000 },
        ranger: { emoji: rankEmojis.ranger || '❌', role: 'Ranger', color: 0x006400 },
        'record chaser': { emoji: rankEmojis.record_chaser || '❌', role: 'Record Chaser', color: 0xff8c00 },
        recruit: { emoji: rankEmojis.recruit || '❌', role: 'Recruit', color: 0x808080 },
        recruiter: { emoji: rankEmojis.recruiter || '❌', role: 'Recruiter', color: 0xdaa520 },
        red: { emoji: rankEmojis.red || '❌', role: 'Red', color: 0xff0000 },
        'red topaz': { emoji: rankEmojis.red_topaz || '❌', role: 'Red Topaz', color: 0xff4500 },
        rogue: { emoji: rankEmojis.rogue || '❌', role: 'Rogue', color: 0x800000 },
        ruby: { emoji: rankEmojis.ruby || '❌', role: 'Ruby', color: 0xe0115f },
        runecrafter: { emoji: rankEmojis.runecrafter || '❌', role: 'Runecrafter', color: 0x8a2be2 },
        sage: { emoji: rankEmojis.sage || '❌', role: 'Sage', color: 0x00ff7f },
        sapphire: { emoji: rankEmojis.sapphire || '❌', role: 'Sapphire', color: 0x0f52ba },
        saradominist: { emoji: rankEmojis.saradominist || '❌', role: 'Saradominist', color: 0xf4a460 },
        saviour: { emoji: rankEmojis.saviour || '❌', role: 'Saviour', color: 0x7fff00 },
        scavenger: { emoji: rankEmojis.scavenger || '❌', role: 'Scavenger', color: 0x556b2f },
        scholar: { emoji: rankEmojis.scholar || '❌', role: 'Scholar', color: 0xbc8f8f },
        scourge: { emoji: rankEmojis.scourge || '❌', role: 'Scourge', color: 0x8b0000 },
        scout: { emoji: rankEmojis.scout || '❌', role: 'Scout', color: 0x40e0d0 },
        scribe: { emoji: rankEmojis.scribe || '❌', role: 'Scribe', color: 0x696969 },
        seer: { emoji: rankEmojis.seer || '❌', role: 'Seer', color: 0x9400d3 },
        senator: { emoji: rankEmojis.senator || '❌', role: 'Senator', color: 0x5f9ea0 },
        sentry: { emoji: rankEmojis.sentry || '❌', role: 'Sentry', color: 0x708090 },
        serenist: { emoji: rankEmojis.serenist || '❌', role: 'Serenist', color: 0x00bfff },
        sergeant: { emoji: rankEmojis.sergeant || '❌', role: 'Sergeant', color: 0x8b0000 },
        shaman: { emoji: rankEmojis.shaman || '❌', role: 'Shaman', color: 0x20b2aa },
        sheriff: { emoji: rankEmojis.sheriff || '❌', role: 'Sheriff', color: 0x00008b },
        'short green guy': { emoji: rankEmojis.short_green_guy || '❌', role: 'Short Green Guy', color: 0x7cfc00 },
        skiller: { emoji: rankEmojis.skiller || '❌', role: 'Skiller', color: 0xdaa520 },
        skulled: { emoji: rankEmojis.skulled || '❌', role: 'Skulled', color: 0x696969 },
        slayer: { emoji: rankEmojis.slayer || '❌', role: 'Slayer', color: 0xdc143c },
        smiter: { emoji: rankEmojis.smiter || '❌', role: 'Smiter', color: 0xff0000 },
        smith: { emoji: rankEmojis.smith || '❌', role: 'Smith', color: 0xd3d3d3 },
        smuggler: { emoji: rankEmojis.smuggler || '❌', role: 'Smuggler', color: 0x8b4513 },
        sniper: { emoji: rankEmojis.sniper || '❌', role: 'Sniper', color: 0x000000 },
        'speed runner': { emoji: rankEmojis.speed_runner || '❌', role: 'Speed Runner', color: 0xff4500 },
        spellcaster: { emoji: rankEmojis.spellcaster || '❌', role: 'Spellcaster', color: 0x8a2be2 },
        squire: { emoji: rankEmojis.squire || '❌', role: 'Squire', color: 0xc0c0c0 },
        staff: { emoji: rankEmojis.staff || '❌', role: 'Staff', color: 0x000080 },
        strider: { emoji: rankEmojis.strider || '❌', role: 'Strider', color: 0x808000 },
        striker: { emoji: rankEmojis.striker || '❌', role: 'Striker', color: 0xff0000 },
        summoner: { emoji: rankEmojis.summoner || '❌', role: 'Summoner', color: 0x9932cc },
        superior: { emoji: rankEmojis.superior || '❌', role: 'Superior', color: 0x00ff00 },
        supervisor: { emoji: rankEmojis.supervisor || '❌', role: 'Supervisor', color: 0x4682b4 },
        teacher: { emoji: rankEmojis.teacher || '❌', role: 'Teacher', color: 0xffff00 },
        templar: { emoji: rankEmojis.templar || '❌', role: 'Templar', color: 0x8b0000 },
        therapist: { emoji: rankEmojis.therapist || '❌', role: 'Therapist', color: 0xff69b4 },
        thief: { emoji: rankEmojis.thief || '❌', role: 'Thief', color: 0x000000 },
        tirannian: { emoji: rankEmojis.tirannian || '❌', role: 'Tirannian', color: 0x800000 },
        trialist: { emoji: rankEmojis.trialist || '❌', role: 'Trialist', color: 0x808080 },
        trickster: { emoji: rankEmojis.trickster || '❌', role: 'Trickster', color: 0xff1493 },
        unholy: { emoji: rankEmojis.unholy || '❌', role: 'Unholy', color: 0x4b0082 },
        vagrant: { emoji: rankEmojis.vagrant || '❌', role: 'Vagrant', color: 0x696969 },
        vanguard: { emoji: rankEmojis.vanguard || '❌', role: 'Vanguard', color: 0x0000ff },
        walker: { emoji: rankEmojis.walker || '❌', role: 'Walker', color: 0x8b4513 },
        wanderer: { emoji: rankEmojis.wanderer || '❌', role: 'Wanderer', color: 0x3cb371 },
        warden: { emoji: rankEmojis.warden || '❌', role: 'Warden', color: 0x8b0000 },
        warlock: { emoji: rankEmojis.warlock || '❌', role: 'Warlock', color: 0x800080 },
        warrior: { emoji: rankEmojis.warrior || '❌', role: 'Warrior', color: 0xb22222 },
        water: { emoji: rankEmojis.water || '❌', role: 'Water', color: 0x1e90ff },
        willow: { emoji: rankEmojis.willow || '❌', role: 'Willow', color: 0x556b2f },
        wily: { emoji: rankEmojis.wily || '❌', role: 'Wily', color: 0xff8c00 },
        wintumber: { emoji: rankEmojis.wintumber || '❌', role: 'Wintumber', color: 0x5f9ea0 },
        witch: { emoji: rankEmojis.witch || '❌', role: 'Witch', color: 0x8a2be2 },
        wizard: { emoji: rankEmojis.wizard || '❌', role: 'Wizard', color: 0x4b0082 },
        worker: { emoji: rankEmojis.worker || '❌', role: 'Worker', color: 0x808080 },
        wrath: { emoji: rankEmojis.wrath || '❌', role: 'Wrath', color: 0xff0000 },
        xerician: { emoji: rankEmojis.xerician || '❌', role: 'Xerician', color: 0x800080 },
        yellow: { emoji: rankEmojis.yellow || '❌', role: 'Yellow', color: 0xffff00 },
        yew: { emoji: rankEmojis.yew || '❌', role: 'Yew', color: 0x228b22 },
        zamorakian: { emoji: rankEmojis.zamorakian || '❌', role: 'Zamorakian', color: 0x8b0000 },
        zarosian: { emoji: rankEmojis.zarosian || '❌', role: 'Zarosian', color: 0x9400d3 },
        zealot: { emoji: rankEmojis.zealot || '❌', role: 'Zealot', color: 0xff6347 },
    };
}

module.exports = { getRanks };
